# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-18 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wish', '0002_auto_20171218_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_hired',
            field=models.DateField(default='', verbose_name='%m/%d/%Y'),
        ),
    ]
